name: Deploy to familytree

on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run scripts in server
        uses: appleboy/ssh-action@master
        env:
          DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
          DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
          DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_KEY }}
          envs: DATABASE_HOST,
            DATABASE_PORT,
            DATABASE_USERNAME,
            DATABASE_PASSWORD,
            DATABASE_NAME

          script: |
            cd family-tree
            mkdir testdir
            git pull origin main
            npm ci
            npm run start
