name: Deploy to familytree

on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run scripts in server
        uses: appleboy/ssh-action@master
        env:
          DATABASE_HOST: { { $secret.DATABASE_HOST } }
          DATABASE_PORT: { { $secret.DATABASE_PORT } }
          DATABASE_USERNAME: { { $secret.DATABASE_USERNAME } }
          DATABASE_PASSWORD: { { $secret.DATABASE_PASSWORD } }
          DATABASE_NAME: { { $secret.DATABASE_NAME } }
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_KEY }}
          envs: DATABASE_HOST,
            DATABASE_PORT,
            DATABASE_USERNAME,
            DATABASE_PASSWORD,
            DATABASE_NAME

          script: |
            cd family-tree
            mkdir testdir
            git pull origin main
            npm ci
            npm run start
